/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liu_orbslam2android_nativefunc_OrbNdkHelper */

#ifndef _Included_com_liu_orbslam2android_nativefunc_OrbNdkHelper
#define _Included_com_liu_orbslam2android_nativefunc_OrbNdkHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liu_orbslam2android_nativefunc_OrbNdkHelper
 * Method:    initSystemWithParameters
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liu_orbslam2android_nativefunc_OrbNdkHelper_initSystemWithParameters
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_liu_orbslam2android_nativefunc_OrbNdkHelper
 * Method:    startCurrentORB
 * Signature: (D[III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_liu_orbslam2android_nativefunc_OrbNdkHelper_startCurrentORB
  (JNIEnv *, jclass, jdouble, jintArray, jint, jint);

/*
 * Class:     com_liu_orbslam2android_nativefunc_OrbNdkHelper
 * Method:    startCurrentORBForCamera
 * Signature: (DJII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_liu_orbslam2android_nativefunc_OrbNdkHelper_startCurrentORBForCamera
  (JNIEnv *, jclass, jdouble, jlong, jint, jint);

/*
 * Class:     com_liu_orbslam2android_nativefunc_OrbNdkHelper
 * Method:    glesInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liu_orbslam2android_nativefunc_OrbNdkHelper_glesInit
  (JNIEnv *, jclass);

/*
 * Class:     com_liu_orbslam2android_nativefunc_OrbNdkHelper
 * Method:    glesRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liu_orbslam2android_nativefunc_OrbNdkHelper_glesRender
  (JNIEnv *, jclass);

/*
 * Class:     com_liu_orbslam2android_nativefunc_OrbNdkHelper
 * Method:    glesResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_liu_orbslam2android_nativefunc_OrbNdkHelper_glesResize
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
